# Generated by Django 5.1 on 2024-08-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
