# Generated by Django 5.1 on 2024-08-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bigsales_img1_bigsales_img2_bigsales_img3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigsales',
            name='img1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bigsales',
            name='img2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bigsales',
            name='img3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bigsales',
            name='img4',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bigsales',
            name='img5',
            field=models.CharField(default='', max_length=500),
        ),
    ]
