# Generated by Django 5.1 on 2024-08-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_bigsales_img1_alter_bigsales_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigsales',
            name='img1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bigsales',
            name='img2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bigsales',
            name='img3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bigsales',
            name='img4',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bigsales',
            name='img5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bigsales',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
