# Generated by Django 5.1 on 2024-08-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_bigsales_img1_alter_bigsales_img2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('img1', models.CharField(default='', max_length=500)),
                ('img2', models.CharField(default='', max_length=500)),
                ('img3', models.CharField(default='', max_length=500)),
                ('img4', models.CharField(default='', max_length=500)),
                ('img5', models.CharField(default='', max_length=500)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('xs', models.BooleanField()),
                ('s', models.BooleanField()),
                ('m', models.BooleanField()),
                ('l', models.BooleanField()),
                ('xl', models.BooleanField()),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
