# Generated by Django 5.1 on 2024-08-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigsales',
            name='tag',
            field=models.CharField(default='New', max_length=15),
        ),
        migrations.AddField(
            model_name='bigsales',
            name='type',
            field=models.CharField(default='Part of Set', max_length=25),
        ),
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.CharField(default='New', max_length=15),
        ),
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.CharField(default='Part of Set', max_length=25),
        ),
    ]
