# Generated by Django 5.1 on 2024-09-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_products_l_alter_products_m_alter_products_s_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
