# Generated by Django 5.1 on 2024-09-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_products_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='newCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('img1', models.CharField(default='', max_length=500)),
                ('img2', models.CharField(default='', max_length=500)),
                ('img3', models.CharField(default='', max_length=500)),
                ('img4', models.CharField(default='', max_length=500)),
                ('img5', models.CharField(default='', max_length=500)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('xs', models.BooleanField()),
                ('s', models.BooleanField()),
                ('m', models.BooleanField()),
                ('l', models.BooleanField()),
                ('xl', models.BooleanField()),
                ('tag', models.CharField(default='New', max_length=15)),
                ('type', models.CharField(default='Part of Set', max_length=25)),
            ],
            options={
                'db_table': 'newCollection',
            },
        ),
        migrations.CreateModel(
            name='winterCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('img1', models.CharField(default='', max_length=500)),
                ('img2', models.CharField(default='', max_length=500)),
                ('img3', models.CharField(default='', max_length=500)),
                ('img4', models.CharField(default='', max_length=500)),
                ('img5', models.CharField(default='', max_length=500)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('xs', models.BooleanField()),
                ('s', models.BooleanField()),
                ('m', models.BooleanField()),
                ('l', models.BooleanField()),
                ('xl', models.BooleanField()),
                ('tag', models.CharField(default='New', max_length=15)),
                ('type', models.CharField(default='Part of Set', max_length=25)),
            ],
            options={
                'db_table': 'winterCollection',
            },
        ),
    ]
