# Generated by Django 5.1 on 2024-09-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_newcollection_wintercollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigsales',
            name='filter',
            field=models.CharField(default='women', max_length=20),
        ),
    ]
