# Generated by Django 5.1 on 2024-09-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_bigsales_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(default='', max_length=25),
        ),
    ]
