# Generated by Django 5.1 on 2024-09-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_products_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='Country',
            field=models.CharField(default='usa', max_length=25),
        ),
        migrations.AddField(
            model_name='personal',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
    ]
