version: '3'

services:
  api:
    build:
      context: ./api
    command: gunicorn --bind 0.0.0.0:8000 mysite.wsgi:application
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    depends_on:
      - db

  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  db:
    image: mariadb:latest
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=your_database_name
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
